### PR TITLE
Giskard MPC - Interface Update

### PR DESCRIPTION
**Pull request by artnie**
Read Giskard's install guide for Gurobi sim and Bullet bindings and update giskardpy and giskard_msgs to `new-interface`:
https://github.com/SemRoCo/giskardpy/tree/new_interface

Test this new interface with iai_pr2_sim: 
https://github.com/code-iai/iai_pr2/tree/master/iai_pr2_sim

Test if your setup is fine with 
`roslaunch cram_pr2_pick_place_demo sandbox_with_giskard.launch`

Launch up rviz, add MarkerArray by topic. Add  and use InteractiveMarkers to test if Giskard responds.

Launch up Emacs and load the `cram_pr2_pick_place_demo`. Then load `cram_pr2_sim_process_modules`. Fire up that roslisp node and hit that demo with `(pr2-sim-pms:with-real-robot (demo::setting-demo))`.

Tested only with PR2 in this setup. Please try on other robots and Unreal.

### CODE REVIEW

**Comment by sunava** [comment]
I think 1 reviewer is enough, will do I today prolly

**Comment by sunava** [comment]
Setting Demo:
Step: before opening the drawer 
**Error:** 

```
PERFORM RESOLVED) INFO] 1654675638.495: 
#<A ACTION
    (TYPE GRIPPING)
    (GRIPPER RIGHT)
    (OBJECT #<A OBJECT
    (NAME IAI-KITCHEN)>)>

[(PERFORM MOTION) INFO] 1654675638.496: 
#<A MOTION
    (TYPE GRIPPING)
    (GRIPPER RIGHT)>

[(PICK-PLACE GRIP) INFO] 1654675638.504: Assert grasp into knowledge base

```


```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CRAM-BULLET-REASONING:ITEM-TYPES (1)>
when called with arguments
  (#<CRAM-BULLET-REASONING:ROBOT-OBJECT {10046D3873}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
```

Giskard:
```

[INFO] [1654675638.456311]: [/giskard]: ----------------Successfully executed goal.----------------
Traceback (most recent call last):
  File "/home/hassouna/cram/giskard_ease_milestone/src/giskardpy/src/giskardpy/tree/behaviors/world_updater.py", line 176, in update_world_cb
    self.update_parent_link(req)
  File "/home/hassouna/cram/giskard_ease_milestone/src/giskardpy/src/giskardpy/tree/behaviors/world_updater.py", line 265, in update_parent_link
    self.world.move_group(req.group_name, req.parent_link)
  File "/home/hassouna/cram/giskard_ease_milestone/src/giskardpy/src/giskardpy/model/world.py", line 535, in move_group
    raise DuplicateNameException(
giskardpy.exceptions.DuplicateNameException: 'iai_kitchen' is already attached to 'map'
```

**Comment by artnie** [comment]
I see, there's been a minor bugfix in giskard that changes the behavior of attachments. Looking into that.

**Comment by artnie** [comment]
The issue was an additional attachment event that is thrown, in the latest merge on noetic. It's this addition:
https://github.com/cram2/cram/blob/95d2944b31de6cc115b33e2e1b7df299d3c7bc7e/cram_3d_world/cram_urdf_environment_manipulation/src/plans.lisp#L132
This causes the whole kitchen to be attached to the pr2's gripper when opening a container, because the gripping action now has an object designator, and if it has an object designator it assumes, that the gripper can hold that object, as is decided here:
https://github.com/cram2/cram/blob/95d2944b31de6cc115b33e2e1b7df299d3c7bc7e/cram_common/cram_mobile_pick_place_plans/src/atomic-action-plans.lisp#L344
Is this the desired behavior? Because releasing the gripper from the container after opening it does not release the attachment.

**Comment by artnie** [comment]
The issue was an additional attachment event that is thrown, in the latest merge on noetic. It's this addition:
https://github.com/cram2/cram/blob/95d2944b31de6cc115b33e2e1b7df299d3c7bc7e/cram_3d_world/cram_urdf_environment_manipulation/src/plans.lisp#L132
This causes the whole kitchen to be attached to the pr2's gripper, because the gripping action now has an object designator, and if it has an object designator it assumes, that the gripper can hold that object, as is decided here:
https://github.com/cram2/cram/blob/95d2944b31de6cc115b33e2e1b7df299d3c7bc7e/cram_common/cram_mobile_pick_place_plans/src/atomic-action-plans.lisp#L344
Is this the desired behavior? Because releasing the gripper from the kitchen does not release the attachment.

**Comment by sunava** [comment]
looking into it.

**Comment by sunava** [comment]
fixed and worked

**Pull request merged**
