### PR TITLE
Knowrob query update for json-prolog-client

### PR DESCRIPTION
**Pull request by artnie**
`prolog->query-string` parses the lisp-prolog expression into a simple string. This conversion is now used in json-prolog:query.
The deprecated code contains an unused lisp-prolog-server and its corresponding functions.

### CODE REVIEW

**Comment by artnie** [comment]
Hey @hawkina would you look at this? ;)

**Comment by artnie** [comment]
You can use the lisp-prolog predicates in the SUTURO json-prolog-client on the master branch to see how they are parsed via `json-prolog:prolog->query-string`. Since on the knowrob side some predicates are deprecated some of the requests won't work when fired against the SUTURO object_state server. On the planning kb_update branch the prolog-simple requests already use the updated queries for the newest knowrob.

**Comment by gaya-** [comment]
@hawkina is the last person using the old KnowRob at the moment. I guess we will merge this PR when she is done with her thesis. Otherwise, let me know if this is more urgent.

**Comment by gaya-** [comment]
Actually, @seba90 already switched to the new KnowRob version, so I've got a dilemma. @hawkina are you going to pull the new version of CRAM for your thesis? And not for a publication for afterwards but specifically until you submit your thesis.

**Comment by gaya-** [comment]
Manually merged in aa2998de, thanks.

**Pull request closed without merging**
