### PR TITLE
 Add cram-urobosim to communicate with unreal 

### PR DESCRIPTION
**Pull request by artnie**
cram-urobosim (aka `unreal`) provides
* a `:detecting` PM and plan to detect objects from Unreal to put them in Bullet
* the service clients to spawn and move objects in a running Unreal world (and stubs to extend to further clients)
* some unused plans for pouring (feeding-plans)

cram-pr2-unreal-process-modules (aka `pr2-unreal-pms`) provides
* an extension to `pr2-pms` as
* the `with-unreal-robot` macro uses unreal-detection, while using the same manipulation pms as `pr2-pms:with-real-robot`

Also a few changes to giskard's constraints, which seemed to be outdated. Giskard won't work without them.

Remove CATKIN_IGNORE in the cram_pr2 packages and cram_external_interfaces/cram_urobosim to build them.

### How to run setting-demo, a very brief guide

Tested with the current [Urobosim DemoProject](https://github.com/urobosim/DemoProject). Open UE and load project. Before `playing` the map, launch rosbridge and urobosim world.
```
roslaunch rosbridge_server rosbridge_websocket.launch
roslaunch urobosim_ros_config world.launch
```
Play the map in Unreal. The PR2 should twitch and wiggle it's arms a bit if it's good. If not, check the DemoProject repo ReadMe how to troubleshoot.
Now launch
```
roslaunch giskardpy giskardpy_pr2_unreal.launch
```
Startup roslisp_repl. First load `cram_pr2_pick_place_demo`, then `cram_pr2_unreal_process_modules`. Start a rosnode with `(roslisp-utilities:startup-ros)`. To start the setting demo, run
```
(pr2-unreal-pms:with-unreal-robot
   (demo::setting-demo '(:spoon)))
```

### Spawn & move objects in Unreal from cram

Run the same launch files as above, but without giskard. Open Emacs, load `cram_urobosim` and start a node. Try to spawn an object with 
```
(unreal:spawn-object :spoon (cl-tf:make-identity-pose))
```

### CODE REVIEW

**Review by sunava — CHANGES_REQUESTED** [review]
have u pulled the latest noetic changes?
When i am checking out your PR the kdl_ik_service is back in cram_external_interfaces, which should not be there.

**Review by sunava — CHANGES_REQUESTED** [review]
Also when loading pick_place demo the following error pop up: Error while trying to load definition for system gsll from
pathname
/home/vanessa/roscram/cram_ws/src/cram/cram_3rdparty/gsll/src/gsll.asd:
i fixed this in cram_noetic is your pr based on melodic maybe?

**Comment by artnie** [comment]
Could you check again? I merged noetic into the pr branch and ran the demo. Here are the CATKIN_IGNOREs that i removed
```
	deleted:    cram_external_interfaces/cram_urobosim/CATKIN_IGNORE
	deleted:    cram_pr2/cram_pr2_low_level/CATKIN_IGNORE
	deleted:    cram_pr2/cram_pr2_process_modules/CATKIN_IGNORE
	deleted:    cram_pr2/cram_pr2_sim_process_modules/CATKIN_IGNORE
	deleted:    cram_pr2/cram_pr2_unreal_process_modules/CATKIN_IGNORE
```

**Comment by sunava** [comment]
@artnie 
I finally got it to work but i had to add: 
- *robosherlock_msgs, unreal_ros_pkgs, urobosim_msgs*  per hand, could this be added to the rosinstall or into iai_common_msgs?
- Why does it depend on the old *pr2_** stuff? We moved all of this to urdf_* to be more generic and the CATKIN_IGNORE is there to show that this pkgs are deprecated
- When i called the demo giskard gave me following error: 
``` 
[ERROR] ..
```
NVM fixed the error :)

**Pull request merged**
